### ISSUE TITLE
console.log(mori_map) fails in 0.3.0 

### ISSUE THREAD

**Issue by tomaskulich** [swannodette/mori#137] opened 2015-01-27 12:22 UTC
it fails consistently for any map or vector; tried this on node v0.10.33

**Comment by swannodette** [comment] 2015-01-27 13:30
@tomaskulich I cannot reproduce this with Node 0.10.35 can you give me the exact steps? Thanks.

**Comment by tomaskulich** [comment] 2015-02-07 21:18
The problem solved somehow in 0.3.1 version, I did not examine, what the problem was. In 0.3.0 just printing the hashMap got my Node (v0.10.33) crashed with:

    > var m = require('mori');
    undefined
    > var a = m.hashMap(1,2,3,4);
    undefined
    > a

    /path/to/myproject
    var l=H(g);b.c?b.c(l,a,f):b.call(null,l,a,f)}for(var m=L(g),p=ja.tc.b(f)-1;;)i
                                                                        ^
    TypeError: Cannot call method 'b' of undefined
        at mh (/home/mama/projo/validation-example-browserify/node_modules/mori/mori.js:366:183)
        at rh (/home/mama/projo/validation-example-browserify/node_modules/mori/mori.js:372:289)
        at jg.v (/home/mama/projo/validation-example-browserify/node_modules/mori/mori.js:375:57)
        at ac (/home/mama/projo/validation-example-browserify/node_modules/mori/mori.js:36:285)
        at jg.k.toString (/home/mama/projo/validation-example-browserify/node_modules/mori/mori.js:293:156)
        at jg.inspect (/home/mama/projo/validation-example-browserify/node_modules/mori/mori.js:425:156)
        at formatValue (util.js:212:25)
        at Object.inspect (util.js:140:10)
        at REPLServer.self.writer (repl.js:177:19)
        at finish (repl.js:291:38)

**Comment by swannodette** [comment] 2015-02-08 04:08
k thanks, closing

**Closed by swannodette** 2015-02-08 04:08 UTC
